# Python - Numpy

In [1]:
# %pip install numpy
import numpy as np

In [2]:
lst = [1,2,3,4,'asihfkdjhfkjsd']

In [3]:
lst

[1, 2, 3, 4, 'asihfkdjhfkjsd']

In [4]:
a = '1'
b = 1

print(a+'1')
print(b+1)

11
2


In [5]:
np.array(lst)

array(['1', '2', '3', '4', 'asihfkdjhfkjsd'], dtype='<U14')

In [6]:
np.array([1,2,3])

array([1, 2, 3])

In [7]:
np.array((1,2,3))

array([1, 2, 3])

In [8]:
np.array({1,2,3})

array({1, 2, 3}, dtype=object)

In [12]:
a = np.array({"a":1, "b":1})
a

array({'a': 1, 'b': 1}, dtype=object)

In [13]:
a.shape

()

In [14]:
np.array([1,2,3,True, False])

array([1, 2, 3, 1, 0])

In [17]:
np.array([True, False, True])

array([ True, False,  True])

In [18]:
np.array([1,2,3,True, False,'abc'])

array(['1', '2', '3', 'True', 'False', 'abc'], dtype='<U11')

In [23]:
if 787:  ## Anything non-zero is True (eg -1,2222,34,-1003)
    print("Hello")
    
if 0: ## 0 means False
    print("World!!")

Hello


In [24]:
np.zeros((3,4))   ## np.zeros(row_number, col_number)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.random.random([3,4])  ## np.random.random((row_numbers, col_numbers)/[row_numbers, col_numbers])

array([[2.32537004e-01, 1.20361919e-01, 8.84847448e-01, 2.09126252e-01],
       [7.18539425e-04, 4.05483670e-01, 1.41035717e-01, 7.04200103e-01],
       [5.32402918e-01, 3.68872971e-03, 1.36106797e-01, 2.28756984e-01]])

In [30]:
np.full((3,4),5.5) ## np.full((row_numbers, col_numbers), number_to_fill)

array([[5.5, 5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5]])

In [32]:
np.arange(1,10,2) ## np.arange(start_num, end_num, difference)

array([1, 3, 5, 7, 9])

In [33]:
np.arange(12) ## np.arange(number_of_elements) ==> Default starts from 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
np.linspace(5,10,7) ## np.linspace(start_num, end_num, num_of_points)

array([ 5.        ,  5.83333333,  6.66666667,  7.5       ,  8.33333333,
        9.16666667, 10.        ])

In [38]:
np.linspace(5,13,5)

array([ 5.,  7.,  9., 11., 13.])

In [39]:
arr = np.array([[1,2,3,4],[1,2,8,7],[2,3,4,6]])

arr

array([[1, 2, 3, 4],
       [1, 2, 8, 7],
       [2, 3, 4, 6]])

In [40]:
arr1 = np.array([[[2,17,19], [45, 78,81], [12, 15,17]], [[88, 92,90], [60, 76,91], [12, 15,17]],[[76,33,50],[20,18,25], [12, 15,17]]])

print(arr1)

[[[ 2 17 19]
  [45 78 81]
  [12 15 17]]

 [[88 92 90]
  [60 76 91]
  [12 15 17]]

 [[76 33 50]
  [20 18 25]
  [12 15 17]]]


In [41]:
arr1.shape

(3, 3, 3)

In [42]:
arr.shape

(3, 4)

In [43]:
arr.ndim

2

In [44]:
arr1.ndim

3

In [45]:
type(arr1)

numpy.ndarray

In [46]:
arr_shape = arr.shape
arr1_shape = arr1.shape


arr_rows = arr_shape[0]
arr_columns = arr_shape[1]

arr1_rows = arr1_shape[0]
arr1_rows_rows = arr1_shape[1]
arr1_rows_columns = arr1_shape[2]

In [47]:
type(arr_shape)

tuple

In [48]:
print(arr_rows, arr_columns, arr1_rows, arr1_rows_rows, arr1_rows_columns)

3 4 3 3 3


In [49]:
arr.dtype

dtype('int32')

In [50]:
a = np.zeros((3,4))

a.dtype

dtype('float64')

In [51]:
a = np.full((3,4), 'abjshdfbkhsjdf')
print(a)
a.dtype

[['abjshdfbkhsjdf' 'abjshdfbkhsjdf' 'abjshdfbkhsjdf' 'abjshdfbkhsjdf']
 ['abjshdfbkhsjdf' 'abjshdfbkhsjdf' 'abjshdfbkhsjdf' 'abjshdfbkhsjdf']
 ['abjshdfbkhsjdf' 'abjshdfbkhsjdf' 'abjshdfbkhsjdf' 'abjshdfbkhsjdf']]


dtype('<U14')

In [52]:
arr1.size

27

In [53]:
arr.size

12

In [54]:
arr = np.arange(12)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
arr = np.arange(1,13,1)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
arr.shape

(12,)

In [57]:
arr = arr.reshape((4,3))

In [58]:
arr.shape

(4, 3)

In [59]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [60]:
a = [[1,  2,  3], [2,  5,  7]]
b = [[1,  2,  3], [3,  5 , 7]]
c = [[1,  3,  5], [1,  2,  3]]

np.equal(a, b)

array([[ True,  True,  True],
       [False,  True,  True]])

In [61]:
np.equal(a, c)

array([[ True, False, False],
       [False, False, False]])

In [62]:
np.equal(b, c)

array([[ True, False, False],
       [False, False, False]])

In [63]:
np.array_equal(a,b)

False

In [64]:
np.array_equal( [[1,  2,  3], [2,  5,  7]], [[1,  2,  3], [2,  5 , 7]])

True

In [65]:
import numpy as np

a = np.array([5,10])
b = np.array([2,3])

print(a)
print(b)

print(np.sum(a))
print(np.sum(b))

print(np.sum([a,b]))

# [
#   5 10
#   2 3
# ]


## Axis = 1 ==> Row wise operation
## Axis = 0 ==> Column wise operation

print(np.sum([a,b], axis=1))
print(np.sum([a,b], axis=0))

[ 5 10]
[2 3]
15
5
20
[15  5]
[ 7 13]


In [66]:
c = np.array([[1,2,4],[3,4,6]])
d = np.array([[2,4,8],[5,7,9]])
print(c)
print("------------------------------------")
print(d)

[[1 2 4]
 [3 4 6]]
------------------------------------
[[2 4 8]
 [5 7 9]]


In [67]:
print(np.sum(c))
print(np.sum(d))

print(np.sum([c,d]))

#[ 
#  [1 2 4
#  3 4 6] 
#]


print(np.sum([c,d],axis=1))
print(np.sum([c,d],axis=0))

20
35
55
[[ 4  6 10]
 [ 7 11 17]]
[[ 3  6 12]
 [ 8 11 15]]


In [68]:
print(np.subtract(c,d))

print(np.multiply(c,d))
print(np.divide(c,d))

print(np.sqrt(c))
print(np.exp(c))
print(np.log(a))
print(np.sin(a))
print(np.cos(a))

[[-1 -2 -4]
 [-2 -3 -3]]
[[ 2  8 32]
 [15 28 54]]
[[0.5        0.5        0.5       ]
 [0.6        0.57142857 0.66666667]]
[[1.         1.41421356 2.        ]
 [1.73205081 2.         2.44948974]]
[[  2.71828183   7.3890561   54.59815003]
 [ 20.08553692  54.59815003 403.42879349]]
[1.60943791 2.30258509]
[-0.95892427 -0.54402111]
[ 0.28366219 -0.83907153]


In [69]:
a = np.array([[1,2,3],[4,5,6]])
print("Sum of the list " , np.sum(a))
print("Minimum elem of the list " , np.min(a))
print("Maximum elem of the list ", np.max(a))


print("Mean of the data points " , np.mean(a))
print("Median of the data points " , np.median(a))

print("Standarad Deviation of the points ", np.std(a))
print("Correlation Coefficient of the list " , np.corrcoef(a))

Sum of the list  21
Minimum elem of the list  1
Maximum elem of the list  6
Mean of the data points  3.5
Median of the data points  3.5
Standarad Deviation of the points  1.707825127659933
Correlation Coefficient of the list  [[1. 1.]
 [1. 1.]]


In [73]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
b = np.array([[3,4,5],[6,7,8]])
print(b)
#axis = 0 => row wise
#axis = 1 => column wise
print("Vertical Concat Resut for axis {} is {}".format(0,np.concatenate([a,b],axis=0)))
print("Horizontal Concat Resut for axis {} is {}".format(1,np.concatenate([a,b],axis=1)))

[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [6 7 8]]
Vertical Concat Resut for axis 0 is [[1 2 3]
 [4 5 6]
 [3 4 5]
 [6 7 8]]
Horizontal Concat Resut for axis 1 is [[1 2 3 3 4 5]
 [4 5 6 6 7 8]]


In [74]:
np.stack((a,b),axis=0)

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 4, 5],
        [6, 7, 8]]])

In [75]:
np.stack((a,b),axis=1)

array([[[1, 2, 3],
        [3, 4, 5]],

       [[4, 5, 6],
        [6, 7, 8]]])

In [76]:
np.hstack([a,b])

array([[1, 2, 3, 3, 4, 5],
       [4, 5, 6, 6, 7, 8]])

In [77]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5],
       [6, 7, 8]])

In [78]:
np.column_stack((a,b))

array([[1, 2, 3, 3, 4, 5],
       [4, 5, 6, 6, 7, 8]])

In [80]:
np.row_stack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5],
       [6, 7, 8]])

In [81]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[2,3,4],[5,6,7]])

print("A Matrix ---")
print(a)
print("B Matrix ---")
print(b)
print("Horizontal Stack---")
print(np.hstack((a,b)))
print("Vertical Concat---")
print(np.concatenate((a,b),axis=1))
print("Column Stack---")
print(np.column_stack((a,b)))

print("Horizontal Concat---")
print(np.concatenate((a,b),axis=0))
print("Vertical Stack---")
print(np.vstack((a,b)))

A Matrix ---
[[1 2 3]
 [4 5 6]]
B Matrix ---
[[2 3 4]
 [5 6 7]]
Horizontal Stack---
[[1 2 3 2 3 4]
 [4 5 6 5 6 7]]
Vertical Concat---
[[1 2 3 2 3 4]
 [4 5 6 5 6 7]]
Column Stack---
[[1 2 3 2 3 4]
 [4 5 6 5 6 7]]
Horizontal Concat---
[[1 2 3]
 [4 5 6]
 [2 3 4]
 [5 6 7]]
Vertical Stack---
[[1 2 3]
 [4 5 6]
 [2 3 4]
 [5 6 7]]


## Number of split should be a factor of total number of elements & it should be lte number of rows or columns based on the direction of operation (either row wise or column wise)

In [83]:
x = np.arange(16).reshape(4,4)
print(x)
print(np.hsplit(x,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])] 



In [84]:
print(np.vsplit(x,2))

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [85]:
print(np.split(x,2,axis = 1))
print(np.split(x,2,axis=0))

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [86]:
x = np.arange(25).reshape(5,5)
print(x)
print(np.hsplit(x,np.array([2,3]))) #x[:,:2], x[:, 2:3], x[:, 3:]
print(np.vsplit(x,np.array([2,3]))) #x[:2,:], x[2:3,:], x[3:,:]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]]), array([[ 2],
       [ 7],
       [12],
       [17],
       [22]]), array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])]
[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])]


In [87]:
import sys

#define a list
l= []

for i in range(10000):
    l.append(i)

print("Size of a type {} of length {} is : {} ".format(type(l),len(l),sys.getsizeof(l[0])*len(l)))

#define a numpy array
a = np.arange(10000)
print("Size of an type {} of length {} is : {} ".format(type(a),a.size, a.size*a.itemsize))

print(f"Numpy array is {(sys.getsizeof(l[0])*len(l)) / (a.size*a.itemsize)} times cheaper than python lists")

Size of a type <class 'list'> of length 10000 is : 240000 
Size of an type <class 'numpy.ndarray'> of length 10000 is : 40000 
Numpy array is 6.0 times cheaper than python lists


In [96]:
sys.getsizeof(l[0])*len(l)

240000

In [97]:
a.itemsize*a.size

40000

In [99]:
X = range(100000)
X

range(0, 100000)

In [100]:
#Numpy vs List: Speed
import time

def using_List():
    t1 = time.time()#Starting/Initial Time
    X = range(100000)
    Y = range(100000)
    z = [X[i]+Y[i] for i in range(len(X))]
    return time.time()-t1

def using_Numpy():
    t1 = time.time()#Starting/Initial Time
    a = np.arange(100000)
    b = np.arange(100000)
    z = a + b #more convient than a list
    return time.time()-t1

list_time = using_List()
numpy_time = using_Numpy()

print("Time taken for list is {} and Time taken for numpy array is {}".format(list_time,numpy_time))
print("In this example Numpy is "+str(list_time/numpy_time)+" times faster than a list")

Time taken for list is 0.06400179862976074 and Time taken for numpy array is 0.007994413375854492
In this example Numpy is 8.005815514001968 times faster than a list
