# Dimensionality Reduction Assignment  
 
Problem Statement:    
You work in XYZ Company as a Python. The company officials want you to write code for reducing the dimensions of a dataset      
 
Tasks to be performed: 
    

- Using load_digits function from sklearn import wines data     

In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_wine

wine=load_wine()

In [2]:
data=pd.DataFrame(data=np.c_[wine['data'],wine['target']],columns=wine['feature_names']+['target'])
data.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0     0.0  
1                          3.40   1050.0     0.0  
2                          3.17   1185.0     0.0  
3                          3.45   1480.0     0.0  
4                          2.93    735.0     0.0

- Take a look at the shape of image data     

In [3]:
print(data.shape)
data.info()

(178, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64


In [4]:
x=pd.DataFrame(data.iloc[:,:-1])
y=pd.DataFrame(data.iloc[:,-1])

- Import PCA, LDA and FactorAnalysis from Sklearn     

In [5]:
from sklearn.decomposition import PCA,LatentDirichletAllocation,FactorAnalysis
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

- Project data in 2 D space using the PCA, LDA and FactorAnalysis algorithm form sklearn                    

In [6]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.25,random_state=0)
pca=PCA(n_components=2)
pca_x_train=pca.fit_transform(xtrain)
pca_x_test=pca.transform(xtest)

In [7]:
pca_x_train

array([[ 9.54445410e+01,  1.39902250e+01],
       [-5.49002358e+01, -5.60700681e+00],
       [ 1.36165698e+02, -1.57529543e+00],
       [ 1.05359747e+02,  9.90153875e+00],
       [ 5.30422666e+02,  1.12889389e+01],
       [-2.19731379e+02,  6.97540923e+00],
       [-1.69985774e+02, -9.80572578e+00],
       [ 4.54666236e+01,  1.57919434e+01],
       [-8.98470753e+01, -9.21424905e-01],
       [ 2.85172934e+02, -3.95829470e+00],
       [-4.37883536e+02, -1.65472575e+00],
       [ 8.54854060e+01,  1.82487252e+01],
       [ 8.01848402e+01,  3.08817706e-01],
       [-3.40017938e+02, -9.08876953e+00],
       [-1.79716691e+02,  8.37962213e+00],
       [-2.69946807e+02, -7.22120688e+00],
       [ 5.35022188e+02, -1.48448664e+01],
       [-2.35039955e+02, -1.17499255e+01],
       [-1.00031692e+02, -1.39251830e+01],
       [-3.21992319e+02, -1.05038784e+01],
       [-3.78066625e+02, -1.46281214e+01],
       [-7.47138656e+01,  6.69239768e+00],
       [-1.19889840e+02, -4.62575130e+00],
       [ 4.

- Take a look at the new data  
 

In [8]:
def perform_pca(n):
    xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.25,random_state=0)
    
    pca=PCA(n_components=n)
    pca_xtrain=pca.fit_transform(xtrain)
    pca_xtest=pca.transform(xtest)
    
    classifier=RandomForestClassifier()
    classifier.fit(pca_xtrain,ytrain)
    ypred=classifier.predict(pca_xtest)
    print("N:",n)
    print("Confusion Matrix:\n",confusion_matrix(ytest,ypred))
    print('Accuracy Score:\n',accuracy_score(ytest,ypred))
    
    
    
    

In [9]:
for i in range(1,10):perform_pca(i)

C:\Users\Mohit Patel\AppData\Local\Temp\ipykernel_1516\152591906.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(pca_xtrain,ytrain)


N: 1
Confusion Matrix:
 [[14  1  1]
 [ 1 14  6]
 [ 2  3  3]]
Accuracy Score:
 0.6888888888888889


C:\Users\Mohit Patel\AppData\Local\Temp\ipykernel_1516\152591906.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(pca_xtrain,ytrain)


N: 2
Confusion Matrix:
 [[14  0  2]
 [ 1 15  5]
 [ 0  4  4]]
Accuracy Score:
 0.7333333333333333


C:\Users\Mohit Patel\AppData\Local\Temp\ipykernel_1516\152591906.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(pca_xtrain,ytrain)


N: 3
Confusion Matrix:
 [[14  0  2]
 [ 0 19  2]
 [ 0  2  6]]
Accuracy Score:
 0.8666666666666667


C:\Users\Mohit Patel\AppData\Local\Temp\ipykernel_1516\152591906.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(pca_xtrain,ytrain)


N: 4
Confusion Matrix:
 [[14  2  0]
 [ 0 20  1]
 [ 0  0  8]]
Accuracy Score:
 0.9333333333333333


C:\Users\Mohit Patel\AppData\Local\Temp\ipykernel_1516\152591906.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(pca_xtrain,ytrain)


N: 5
Confusion Matrix:
 [[14  2  0]
 [ 0 21  0]
 [ 0  0  8]]
Accuracy Score:
 0.9555555555555556


C:\Users\Mohit Patel\AppData\Local\Temp\ipykernel_1516\152591906.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(pca_xtrain,ytrain)


N: 6
Confusion Matrix:
 [[15  1  0]
 [ 0 21  0]
 [ 0  0  8]]
Accuracy Score:
 0.9777777777777777


C:\Users\Mohit Patel\AppData\Local\Temp\ipykernel_1516\152591906.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(pca_xtrain,ytrain)


N: 7
Confusion Matrix:
 [[15  1  0]
 [ 0 20  1]
 [ 0  0  8]]
Accuracy Score:
 0.9555555555555556


C:\Users\Mohit Patel\AppData\Local\Temp\ipykernel_1516\152591906.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(pca_xtrain,ytrain)


N: 8
Confusion Matrix:
 [[15  1  0]
 [ 0 21  0]
 [ 0  0  8]]
Accuracy Score:
 0.9777777777777777


C:\Users\Mohit Patel\AppData\Local\Temp\ipykernel_1516\152591906.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(pca_xtrain,ytrain)


N: 9
Confusion Matrix:
 [[15  1  0]
 [ 0 20  1]
 [ 0  0  8]]
Accuracy Score:
 0.9555555555555556
