# Tasks to be performed:

1. Create a 3x3 matrix array with values ranging from 2 to 10.

In [3]:
import numpy as np
a=np.arange(2,11)
b=a.reshape(3,3)
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

2. Create a numpy array having user inputs and convert the type to the float type of the elements of the array. for instance:

original array=[1,2,3,4]


In [8]:
list=[1,2,3,4]
array1=np.array(list)
print("Array:\n",array1)
array1.dtype

Array:
 [1 2 3 4]


dtype('int32')

In [9]:
# converted Array:
arr=np.asfarray(array1)
arr.dtype


dtype('float64')

3. Write a numpy program to append valus to the end of an array. for instance:

* Original array: [10,20,30]

* After append values to the end of the array:[10,20,30,40,50,60,70,80,90]

In [17]:
#Creating array:
org_array=[10,20,30]
a=np.array(org_array)
a


array([10, 20, 30])

In [18]:
#appending the element in the array:
org_array.append(40)
org_array.append(50)
org_array.append(60)
org_array.append(70)
org_array.append(80)
org_array.append(90)

a=np.array(org_array)
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

4.Create two numpy arrays and add the elements of both the arrays and store the result in sumArray.

In [20]:
import numpy as np 
array1=np.array([1,2,3,4])
array2=np.array([2,3,4,5,6])
print(array1)
print(array2)


[1 2 3 4]
[2 3 4 5 6]


In [26]:
#Sum of array:
a=np.sum(array1)
print(a)
b=np.sum(array2)
print(b)
c=np.array([a,b])
c

10
20


array([10, 20])

5. Create a 3x3 array having the values from 10-90 (interval of 10) and store that in array1. Perform the followings tasks:
* Extract the 1st row from the array.
* Extract the last element from the array


In [28]:
# Creating the array:
array1=np.arange(10,100,10)
print(array1)

[10 20 30 40 50 60 70 80 90]


In [33]:
# change it into 3x3 matrix :
a=array1.reshape(3,3)
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [35]:
# a. EXtracting the first row of the array:
a[:1]

array([[10, 20, 30]])

In [36]:
# b. Extract last element of the array:
a[2:,2:]

array([[90]])