In [2]:
import numpy as np

# Task to be performed:

1. Create a function that takes dimensions as tuples e.g. (3,3) and a numeric value and returns a Numpy array of the given dimension filled with the given values e.g.:solve((3,3),5) will return.

In [3]:
def array1(x,y,z):
    a=np.full((x,y),z)
    return a

In [4]:
array1(3,3,5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

2.Create method that takes n numpy arrays of same dimensions sums them and return the answer.

In [21]:
# Review it: now done
def sum_of_arrays():
    a=[]
    s=int(input("Number of arrays:"))
    y=int(input("no. of elements:"))
    for i in range(s):
        b=[]
        for j in range(y):
            c=int(input())
            b.append(c)
        a.append(b)
        print("Array",i,":",b)
    x=np.array(a)
    print("Sum of arrays:",np.sum(x,axis=0))
    print("Sum of arrays:",np.sum(x,axis=1))
    
    

In [22]:
sum_of_arrays()

Array 0 : [1, 2, 3]
Array 1 : [4, 5, 6]
Array 2 : [7, 8, 9]
Array 3 : [4, 2, 6]
Sum of arrays: [16 17 24]
Sum of arrays: [ 6 15 24 12]


In [20]:
a=np.array([[10,21,34,54],[33,45,34,55]])
b=np.array([[3,4,5,6],[8,90,78,45]])
print("Array1:\n",a)
print("Array2:\n",b)
c=np.sum((a,b))
print("sum of array:\n",c)

Array1:
 [[10 21 34 54]
 [33 45 34 55]]
Array2:
 [[ 3  4  5  6]
 [ 8 90 78 45]]
sum of array:
 525


In [ ]:
print(np.sum((a,b),axis=0))

[[ 13  25  39  60]
 [ 41 135 112 100]]


In [ ]:
print(np.sum((a,b),axis=1))


[[ 43  66  68 109]
 [ 11  94  83  51]]


In [ ]:
print(np.sum((a,b),axis=2))


[[119 167]
 [ 18 221]]


3. Give a 2D Array of N*M dimensions, write a function that accepts this array as well as two numbers N and M. The method should return the top left N*M sub matrix e.g.

In [ ]:
import numpy as np 
a=np.arange(1,10).reshape(3,3)
print(a)

# Top left Sub-matrix:2*2
a[:2,:2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2],
       [4, 5]])

4. Give a 2D Array of N X M dimensions, write a function that accepts this array as well as two numbers N and M. The method should return the right bottom N X M sub matrix.

In [ ]:
import numpy as np
b=np.arange(1,10)
print(b)
c=b.reshape(3,3)
print(c)

# Slicing the array from a matrix right bottom:
c[1:,1:]

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[5, 6],
       [8, 9]])

5. Given a 1D array. Write a function that accepts this array as parameters. The method should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's standard deviation  as values:

In [ ]:
a=np.array([12,33,43])
def fun1(a):
    mean=a.mean()
    std_dev=a.std()
    return {'mean':mean,'std_dev':std_dev}

In [ ]:
fun1(a)

{'mean': 29.333333333333332, 'std_dev': 12.918548250050733}